import mongoose from "mongoose";
import dotenv from "dotenv";
import Product from "../models/Product.js";

dotenv.config();

const PRODUCTS = [
  // ==================== APPLIANCES & REFRIGERATORS ====================
  {
    name: "LG 260L 3-Star Smart Inverter Double Door Refrigerator",
    brand: "LG",
    category: "Appliances",
    description: "Door Cooling+ technology with Smart Inverter Compressor and multi-air flow vents.",
    price: 26990,
    originalPrice: 34990,
    rating: 4.8,
    reviews: 420,
    stock: 12,
    image: "https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?w=800&auto=format&fit=crop&q=80",
    specifications: { Type: "Double Door", Capacity: "260 Litres", StarRating: "3 Star" },
  },
  {
    name: "Samsung 324L 3-Star Convertible 5-in-1 Refrigerator",
    brand: "Samsung",
    category: "Appliances",
    description: "Digital Inverter with Twin Cooling Plus converts freezer to extra fridge space.",
    price: 33990,
    originalPrice: 42990,
    rating: 4.7,
    reviews: 310,
    stock: 15,
    image: "https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?w=800&auto=format&fit=crop&q=80",
    specifications: { Type: "Double Door Convertible", Capacity: "324 Litres", Modes: "5-in-1" },
  },
  {
    name: "Whirlpool 240L Protton Triple Door Frost-Free Refrigerator",
    brand: "Whirlpool",
    category: "Appliances",
    description: "Unique three-door layout prevents odor mixing and features Zeolite fresh technology.",
    price: 25490,
    originalPrice: 31990,
    rating: 4.6,
    reviews: 280,
    stock: 18,
    image: "https://images.unsplash.com/photo-1584992236310-6edddc08acff?w=800&auto=format&fit=crop&q=80",
    specifications: { Type: "Triple Door", Capacity: "240 Litres", Feature: "Zeolite Technology" },
  },
  {
    name: "Haier 531L Side-by-Side Inverter Refrigerator",
    brand: "Haier",
    category: "Appliances",
    description: "Twin Inverter side-by-side refrigerator with 90-degree door opening and holiday mode.",
    price: 56990,
    originalPrice: 72990,
    rating: 4.9,
    reviews: 140,
    stock: 6,
    image: "https://images.unsplash.com/photo-1590725140246-20acdee442be?w=800&auto=format&fit=crop&q=80",
    specifications: { Type: "Side-by-Side", Capacity: "531 Litres", Compressor: "Twin Inverter" },
  },
  {
    name: "Bosch Serie 6 8kg 1400RPM Front Load Washing Machine",
    brand: "Bosch",
    category: "Appliances",
    description: "EcoSilence Drive motor with Anti-Tangle program and built-in hot water heater.",
    price: 36990,
    originalPrice: 44990,
    rating: 4.8,
    reviews: 510,
    stock: 14,
    image: "https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?w=800&auto=format&fit=crop&q=80",
    specifications: { Type: "Front Load", Capacity: "8.0 kg", MaxRPM: "1400 RPM" },
  },
  {
    name: "Daikin 1.5 Ton 5-Star Inverter Split AC",
    brand: "Daikin",
    category: "Appliances",
    description: "100% grooved copper condenser with Coanda airflow and PM2.5 particulate filter.",
    price: 37990,
    originalPrice: 48990,
    rating: 4.7,
    reviews: 630,
    stock: 20,
    image: "https://images.unsplash.com/photo-1614633833026-062040439d09?w=800&auto=format&fit=crop&q=80",
    specifications: { Tonnage: "1.5 Ton", StarRating: "5 Star", Condenser: "100% Copper" },
  },
  {
    name: "Panasonic 27L Convection Microwave Oven",
    brand: "Panasonic",
    category: "Appliances",
    description: "Zero-oil cooking with 101 auto-cook menus and 360-degree glass turntable.",
    price: 11490,
    originalPrice: 15490,
    rating: 4.5,
    reviews: 320,
    stock: 22,
    image: "https://images.unsplash.com/photo-1574269909862-7e1d70bb8078?w=800&auto=format&fit=crop&q=80",
    specifications: { Type: "Convection & Grill", Capacity: "27 Litres", Power: "900W" },
  },
  {
    name: "Sony Bravia 55-inch 4K Google Smart TV",
    brand: "Sony",
    category: "Appliances",
    description: "4K HDR Processor X1 with Live Color and built-in Google Assistant Chromecast.",
    price: 57990,
    originalPrice: 74990,
    rating: 4.9,
    reviews: 450,
    stock: 10,
    image: "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=800&auto=format&fit=crop&q=80",
    specifications: { Size: "55 Inch", Display: "4K HDR", OS: "Google TV" },
  },

  // ==================== FOOTWEAR (Each Item Has A Distinct Photo) ====================
  {
    name: "Nike Air Zoom Pegasus 40 Red/Black",
    brand: "Nike",
    category: "Footwear",
    description: "Responsive React foam midsole with engineered breathable mesh.",
    price: 9495,
    originalPrice: 11995,
    rating: 4.7,
    reviews: 410,
    stock: 25,
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&auto=format&fit=crop&q=80",
    specifications: { Sole: "React Foam", Style: "Road Running" },
  },
  {
    name: "Adidas Originals Superstar White/Black Shell-Toe",
    brand: "Adidas",
    category: "Footwear",
    description: "Authentic full-grain leather classic with serrated stripes and rubber cupsole.",
    price: 7999,
    originalPrice: 8999,
    rating: 4.6,
    reviews: 620,
    stock: 30,
    image: "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=800&auto=format&fit=crop&q=80",
    specifications: { Material: "Leather", Toe: "Shell Toe" },
  },
  {
    name: "Puma RS-X Triple White Chunky Trainer",
    brand: "Puma",
    category: "Footwear",
    description: "Chunky sole with running system shock absorption and mesh accents.",
    price: 5499,
    originalPrice: 9999,
    rating: 4.4,
    reviews: 190,
    stock: 15,
    image: "https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=800&auto=format&fit=crop&q=80",
    specifications: { Type: "Lifestyle Chunky", Midsole: "PU" },
  },
  {
    name: "New Balance 574 Core Grey Heritage",
    brand: "New Balance",
    category: "Footwear",
    description: "Premium grey cow suede with breathable mesh on an ENCAP supportive rim.",
    price: 8499,
    originalPrice: 9999,
    rating: 4.8,
    reviews: 370,
    stock: 14,
    image: "https://images.unsplash.com/photo-1539185441755-769473a23570?w=800&auto=format&fit=crop&q=80",
    specifications: { Support: "ENCAP", Upper: "Suede / Mesh" },
  },
  {
    name: "Timberland 6-Inch Premium Yellow Nubuck Boot",
    brand: "Timberland",
    category: "Footwear",
    description: "Seam-sealed waterproof Nubuck leather with warm PrimaLoft insulation.",
    price: 16990,
    originalPrice: 19990,
    rating: 4.9,
    reviews: 310,
    stock: 11,
    image: "https://images.unsplash.com/photo-1520639888713-7851133b1ed0?w=800&auto=format&fit=crop&q=80",
    specifications: { Waterproof: "Yes", Collar: "Padded Leather" },
  },
  {
    name: "Vans Old Skool Black & White Skate Shoes",
    brand: "Vans",
    category: "Footwear",
    description: "Durable canvas and suede low top with vulcanized waffle outsole.",
    price: 4499,
    originalPrice: 4999,
    rating: 4.5,
    reviews: 730,
    stock: 40,
    image: "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=800&auto=format&fit=crop&q=80",
    specifications: { Outsole: "Rubber Waffle", Construction: "Vulcanized" },
  },
  {
    name: "Converse Chuck Taylor All Star Red Canvas",
    brand: "Converse",
    category: "Footwear",
    description: "Classic high-top canvas ankle shoe with heritage rubber toe bumper.",
    price: 3999,
    originalPrice: 4499,
    rating: 4.6,
    reviews: 840,
    stock: 35,
    image: "https://images.unsplash.com/photo-1607522370275-f14206abe5d3?w=800&auto=format&fit=crop&q=80",
    specifications: { Style: "High Top", Upper: "Canvas" },
  },
  {
    name: "Crocs Classic Navy Slip-On Clog",
    brand: "Crocs",
    category: "Footwear",
    description: "Ultra-lightweight waterproof Croslite foam with pivoting heel strap.",
    price: 2495,
    originalPrice: 2995,
    rating: 4.7,
    reviews: 1200,
    stock: 60,
    image: "https://images.unsplash.com/photo-1603808033192-082d6919d3e1?w=800&auto=format&fit=crop&q=80",
    specifications: { Material: "Croslite Foam", WaterFriendly: "Yes" },
  },

  // ==================== ELECTRONICS ====================
  {
    name: "Sony WH-1000XM5 Matte Black Headphones",
    brand: "Sony",
    category: "Electronics",
    description: "Noise cancelling headphones with 30-hour playback and dual processors.",
    price: 26990,
    originalPrice: 34990,
    rating: 4.9,
    reviews: 510,
    stock: 16,
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80",
    specifications: { Battery: "30h", Bluetooth: "5.2" },
  },
  {
    name: "Apple Watch Series 9 Starlight Case",
    brand: "Apple",
    category: "Electronics",
    description: "Always-on OLED screen with ECG, blood oxygen, and crash detection.",
    price: 41900,
    originalPrice: 44900,
    rating: 4.8,
    reviews: 430,
    stock: 12,
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=80",
    specifications: { Case: "45mm Aluminum", Waterproof: "50m" },
  },
  {
    name: "Dell UltraSharp 27-inch 4K USB-C Monitor",
    brand: "Dell",
    category: "Electronics",
    description: "IPS Black display with 2000:1 contrast ratio and 90W laptop charging.",
    price: 54990,
    originalPrice: 62000,
    rating: 4.7,
    reviews: 130,
    stock: 8,
    image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&auto=format&fit=crop&q=80",
    specifications: { Resolution: "3840 x 2160", Port: "USB-C 90W PD" },
  },
  {
    name: "Logitech MX Master 3S Wireless Mouse",
    brand: "Logitech",
    category: "Electronics",
    description: "Silent 8000 DPI tracking on any glass surface with MagSpeed scroll.",
    price: 9495,
    originalPrice: 10995,
    rating: 4.9,
    reviews: 790,
    stock: 28,
    image: "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=800&auto=format&fit=crop&q=80",
    specifications: { DPI: "8000", Battery: "70 Days" },
  },
  {
    name: "Keychron K2 75% Mechanical Keyboard",
    brand: "Keychron",
    category: "Electronics",
    description: "Wireless mechanical keyboard with Gateron brown tactile switches.",
    price: 7999,
    originalPrice: 9499,
    rating: 4.6,
    reviews: 260,
    stock: 19,
    image: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&auto=format&fit=crop&q=80",
    specifications: { Layout: "75%", Connectivity: "Bluetooth & USB-C" },
  },
  {
    name: "Sony Alpha 7 IV Full-Frame Camera",
    brand: "Sony",
    category: "Electronics",
    description: "33MP Full-Frame mirrorless camera with 4K 60p 10-bit recording.",
    price: 209990,
    originalPrice: 242000,
    rating: 4.9,
    reviews: 98,
    stock: 5,
    image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&auto=format&fit=crop&q=80",
    specifications: { Sensor: "33MP CMOS", Mount: "Sony E" },
  },

  // ==================== FASHION ====================
  {
    name: "Levi's Original Trucker Denim Jacket",
    brand: "Levi's",
    category: "Fashion",
    description: "Standard fit 100% heavy cotton rigid denim jacket with metal shank buttons.",
    price: 4999,
    originalPrice: 6599,
    rating: 4.7,
    reviews: 320,
    stock: 22,
    image: "https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=800&auto=format&fit=crop&q=80",
    specifications: { Fabric: "100% Cotton Denim", Fit: "Standard" },
  },
  {
    name: "Zara Pure Linen Button-Down Shirt",
    brand: "Zara",
    category: "Fashion",
    description: "Breathable pure linen woven shirt cut with a relaxed spread collar.",
    price: 3290,
    originalPrice: 3990,
    rating: 4.4,
    reviews: 140,
    stock: 24,
    image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&auto=format&fit=crop&q=80",
    specifications: { Material: "100% Linen", Sleeves: "Full" },
  },
  {
    name: "Ray-Ban Classic Gold Aviator Sunglasses",
    brand: "Ray-Ban",
    category: "Fashion",
    description: "Gold metal teardrop frames with crystal green G-15 UV400 lenses.",
    price: 10890,
    originalPrice: 12290,
    rating: 4.9,
    reviews: 460,
    stock: 14,
    image: "https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=800&auto=format&fit=crop&q=80",
    specifications: { Lens: "G-15 Mineral Glass", Protection: "UV400" },
  },
  {
    name: "Fossil Townsman Automatic Skeleton Watch",
    brand: "Fossil",
    category: "Fashion",
    description: "Self-winding open rotor dial with brown genuine leather strap.",
    price: 17495,
    originalPrice: 20995,
    rating: 4.7,
    reviews: 180,
    stock: 9,
    image: "https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=800&auto=format&fit=crop&q=80",
    specifications: { Movement: "Automatic", Dial: "Skeleton Dial" },
  },
// ==================== SMARTPHONES / MOBILES ====================
  {
    name: "Apple iPhone 15 Pro Max (256 GB) - Natural Titanium",
    brand: "Apple",
    category: "Electronics",
    description: "Forged in titanium with A17 Pro chip, customizable Action button, and 48MP camera.",
    price: 134900,
    originalPrice: 159900,
    rating: 4.9,
    reviews: 1420,
    stock: 25,
    image: "https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800&auto=format&fit=crop&q=80",
    specifications: { Screen: "6.7-inch Super Retina XDR", Processor: "A17 Pro", Storage: "256GB" }
  },
  {
    name: "Samsung Galaxy S24 Ultra 5G (Titanium Gray, 12GB RAM, 512GB Storage)",
    brand: "Samsung",
    category: "Electronics",
    description: "Galaxy AI features, 200MP camera system, built-in S Pen, and Snapdragon 8 Gen 3.",
    price: 129999,
    originalPrice: 144999,
    rating: 4.8,
    reviews: 980,
    stock: 18,
    image: "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800&auto=format&fit=crop&q=80",
    specifications: { Screen: "6.8-inch Dynamic AMOLED 2X", RAM: "12GB", S_Pen: "Included" }
  },
  {
    name: "OnePlus 12 5G (Flowy Emerald, 16GB RAM, 512GB Storage)",
    brand: "OnePlus",
    category: "Electronics",
    description: "Snapdragon 8 Gen 3 with 4th Gen Hasselblad Camera and 100W SUPERVOOC charging.",
    price: 64999,
    originalPrice: 69999,
    rating: 4.7,
    reviews: 650,
    stock: 20,
    image: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=800&auto=format&fit=crop&q=80",
    specifications: { Charging: "100W Fast Charge", Display: "2K 120Hz ProXDR", Battery: "5400mAh" }
  },
  {
    name: "Google Pixel 8 Pro (Obsidian, 128GB)",
    brand: "Google",
    category: "Electronics",
    description: "Engineered by Google with Tensor G3 chip, advanced Pixel cameras, and 7 years of updates.",
    price: 79999,
    originalPrice: 106999,
    rating: 4.6,
    reviews: 410,
    stock: 15,
    image: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&auto=format&fit=crop&q=80",
    specifications: { Camera: "50MP Triple System", Chip: "Google Tensor G3", Screen: "6.7-inch Super Actua" }
  },
  {
    name: "Xiaomi 14 Ultra (White, 16GB RAM, 512GB Storage)",
    brand: "Xiaomi",
    category: "Electronics",
    description: "Leica quad camera system with 1-inch variable aperture sensor and WQHD+ AMOLED.",
    price: 99999,
    originalPrice: 119999,
    rating: 4.7,
    reviews: 290,
    stock: 10,
    image: "https://images.unsplash.com/photo-1580910051074-3eb694886505?w=800&auto=format&fit=crop&q=80",
    specifications: { Optics: "Leica Quad Camera", Screen: "WQHD+ 120Hz AMOLED", Charging: "90W HyperCharge" }
  },// ==================== SMARTPHONES / MOBILES ====================
  {
    name: "Apple iPhone 15 Pro Max (256 GB) - Natural Titanium",
    brand: "Apple",
    category: "Electronics",
    description: "Forged in titanium with A17 Pro chip, customizable Action button, and 48MP camera.",
    price: 134900,
    originalPrice: 159900,
    rating: 4.9,
    reviews: 1420,
    stock: 25,
    image: "https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800&auto=format&fit=crop&q=80",
    specifications: { Screen: "6.7-inch Super Retina XDR", Processor: "A17 Pro", Storage: "256GB" }
  },
  {
    name: "Samsung Galaxy S24 Ultra 5G (Titanium Gray, 12GB RAM, 512GB Storage)",
    brand: "Samsung",
    category: "Electronics",
    description: "Galaxy AI features, 200MP camera system, built-in S Pen, and Snapdragon 8 Gen 3.",
    price: 129999,
    originalPrice: 144999,
    rating: 4.8,
    reviews: 980,
    stock: 18,
    image: "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800&auto=format&fit=crop&q=80",
    specifications: { Screen: "6.8-inch Dynamic AMOLED 2X", RAM: "12GB", S_Pen: "Included" }
  },
  {
    name: "OnePlus 12 5G (Flowy Emerald, 16GB RAM, 512GB Storage)",
    brand: "OnePlus",
    category: "Electronics",
    description: "Snapdragon 8 Gen 3 with 4th Gen Hasselblad Camera and 100W SUPERVOOC charging.",
    price: 64999,
    originalPrice: 69999,
    rating: 4.7,
    reviews: 650,
    stock: 20,
    image: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=800&auto=format&fit=crop&q=80",
    specifications: { Charging: "100W Fast Charge", Display: "2K 120Hz ProXDR", Battery: "5400mAh" }
  },
  {
    name: "Google Pixel 8 Pro (Obsidian, 128GB)",
    brand: "Google",
    category: "Electronics",
    description: "Engineered by Google with Tensor G3 chip, advanced Pixel cameras, and 7 years of updates.",
    price: 79999,
    originalPrice: 106999,
    rating: 4.6,
    reviews: 410,
    stock: 15,
    image: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&auto=format&fit=crop&q=80",
    specifications: { Camera: "50MP Triple System", Chip: "Google Tensor G3", Screen: "6.7-inch Super Actua" }
  },
  {
    name: "Xiaomi 14 Ultra (White, 16GB RAM, 512GB Storage)",
    brand: "Xiaomi",
    category: "Electronics",
    description: "Leica quad camera system with 1-inch variable aperture sensor and WQHD+ AMOLED.",
    price: 99999,
    originalPrice: 119999,
    rating: 4.7,
    reviews: 290,
    stock: 10,
    image: "https://images.unsplash.com/photo-1580910051074-3eb694886505?w=800&auto=format&fit=crop&q=80",
    specifications: { Optics: "Leica Quad Camera", Screen: "WQHD+ 120Hz AMOLED", Charging: "90W HyperCharge" }
  },
  // ==================== HOME ====================
  {
    name: "IKEA Markus Ergonomic High-Back Chair",
    brand: "IKEA",
    category: "Home",
    description: "High-back mesh support with tilt tension adjustment for long work sessions.",
    price: 14990,
    originalPrice: 17990,
    rating: 4.7,
    reviews: 410,
    stock: 11,
    image: "https://images.unsplash.com/photo-1580481077195-c3c1e30928b4?w=800&auto=format&fit=crop&q=80",
    specifications: { Material: "Aluminium & Mesh", WeightCap: "110 kg" },
  },
  {
    name: "Marshall Acton III Home Bluetooth Speaker",
    brand: "Marshall",
    category: "Home",
    description: "Iconic brass hardware and acoustic stereo sound with Bluetooth 5.2.",
    price: 29999,
    originalPrice: 32999,
    rating: 4.9,
    reviews: 260,
    stock: 7,
    image: "https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&auto=format&fit=crop&q=80",
    specifications: { Wattage: "60W Class D", Controls: "Analog Brass Knobs" },
  },
  {
    name: "Dyson Purifier Cool Gen1 HEPA Air Purifier",
    brand: "Dyson",
    category: "Home",
    description: "Sealed HEPA H13 filtration removes 99.95% of ultrafine pollutants.",
    price: 32900,
    originalPrice: 39900,
    rating: 4.7,
    reviews: 190,
    stock: 10,
    image: "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=800&auto=format&fit=crop&q=80",
    specifications: { Filter: "HEPA H13", Oscillation: "350 Degrees" },
  },
  {
    name: "Artisan Stoneware Ceramic Coffee Mug Set",
    brand: "ComfortPlus",
    category: "Home",
    description: "Hand-thrown stoneware clay mugs with reactive glaze finish.",
    price: 1299,
    originalPrice: 1899,
    rating: 4.9,
    reviews: 150,
    stock: 50,
    image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&auto=format&fit=crop&q=80",
    specifications: { Capacity: "380 ml", MicrowaveSafe: "Yes" },
  }
];

const seedDB = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log("Connected to MongoDB...");

    await Product.deleteMany();
    console.log("Purged old records...");

    const finalDocs = PRODUCTS.map((item) => {
      const original = item.originalPrice || Math.round(item.price * 1.25);
      const discount = Math.round(((original - item.price) / original) * 100);
      return {
        ...item,
        originalPrice: original,
        discount,
        images: [item.image],
        featured: item.rating >= 4.8,
      };
    });

    await Product.insertMany(finalDocs);
    console.log(`Success: Seeded ${finalDocs.length} completely unique items with distinct photos.`);
    process.exit(0);
  } catch (err) {
    console.error("Seeding Error:", err);
    process.exit(1);
  }
};

seedDB();